### ISSUE TITLE
keep get message "temp path failed, please create"

### ISSUE THREAD

**Issue by howardhee** [lurrpis/zip-online-file-php#1]
When i click the submit button, got that error. How and where do i create a temp folder path for my project?

**Comment by lurpis** [comment]
Hi, your project do not have permission to create a folder.
You can manually create or modify the permissions

Please  git pull first.

```
cd example
mkdir temp
chmod -R 755 temp
```

or

```
chmod -R 777 example
```

**Comment by howardhee** [comment]
I already manually create a folder. After I deploy to remote server, i run and get the error.
